<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>JackDebug</RootNamespace>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>JackDebug.WPF</RootNamespace>
    <UseWPF>true</UseWPF>
    <ImportedNamespaces>System.Drawing=False,Microsoft.VisualBasic=True,System=True,System.Collections=True,System.Collections.Generic=True,System.Diagnostics=True,System.Linq=True,System.Xml.Linq=True,System.Threading.Tasks=True,JackDebug=True</ImportedNamespaces>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    <ApplicationManifest>My Project\app.manifest</ApplicationManifest>
    <Title>Jack Debug (WPF)</Title>
    <Company>JackOfFates</Company>
    <Description>Debug your WPF application easily with JackDebug.</Description>
    <PackageProjectUrl>https://JackOfAllFates.com/</PackageProjectUrl>
    <PackageIcon>JackDebug(1).png</PackageIcon>
    <PackageReleaseNotes>Added recursive functionality.</PackageReleaseNotes>
    <PackageTags>Debug; Debugging; Visual; Graphing; Graph; Variables; Variable; Runtime; Realtime; Live</PackageTags>
    <Copyright>Copyright © JackOfFates 2024</Copyright>
    <Version>1.4.0.0</Version>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/JackOfFates/Jack-Debug</RepositoryUrl>
	  <IsPackable>True</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="favicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
    <PackageReference Include="SocketJack.WPF" Version="1.4.5" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.3" />
  </ItemGroup>
	
  <ItemGroup>
    <Import Include="System.Drawing" />
  </ItemGroup>
	
  <ItemGroup>
    <None Include="..\..\..\..\Downloads\JackDebug(1).png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\..\..\Downloads\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\SocketJack\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
	
  <ItemGroup>
    <Compile Update="My Project\Resources.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
	
  <ItemGroup>
    <EmbeddedResource Update="My Project\Resources.resx">
      <CustomToolNamespace>My.Resources</CustomToolNamespace>
      <Generator>VbMyResourcesResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.vb</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
	
  <ItemGroup>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
