<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>JackDebug</RootNamespace>
    <TargetFrameworks>
		net9.0-windows10.0.26100.0;net9.0-windows10.0.22621.0;net9.0-windows10.0.20348.0;net9.0-windows10.0.19041.0;net9.0-windows10.0.18362.0;net9.0-windows10.0.17763.0;net8.0-windows10.0.26100.0;net8.0-windows10.0.22621.0;net8.0-windows10.0.20348.0;net8.0-windows10.0.19041.0;net8.0-windows10.0.18362.0;net8.0-windows10.0.17763.0;net7.0-windows10.0.26100.0;net7.0-windows10.0.22621.0;net7.0-windows10.0.20348.0;net7.0-windows10.0.19041.0;net7.0-windows10.0.18362.0;net7.0-windows10.0.17763.0;net6.0-windows10.0.26100.0;net6.0-windows10.0.22621.0;net6.0-windows10.0.20348.0;net6.0-windows10.0.19041.0;net6.0-windows10.0.18362.0;net6.0-windows10.0.17763.0;net6.0-windows8.0;net6.0-windows7.0;net7.0-windows8.0;net7.0-windows7.0;net8.0-windows8.0;net8.0-windows7.0;net9.0-windows8.0;net9.0-windows7.0;
	</TargetFrameworks>
    <RootNamespace>JackDebug.WPF</RootNamespace>
    <UseWPF>true</UseWPF>
    <ImportedNamespaces>System.Drawing=False,Microsoft.VisualBasic=True,System=True,System.Collections=True,System.Collections.Generic=True,System.Diagnostics=True,System.Linq=True,System.Xml.Linq=True,System.Threading.Tasks=True,JackDebug=True</ImportedNamespaces>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    <ApplicationManifest>My Project\app.manifest</ApplicationManifest>
    <Title>Jack Debug (WPF)</Title>
    <Company>JackOfFates</Company>
    <Description>Debug your WPF application easily with JackDebug.</Description>
    <PackageProjectUrl>https://JackOfAllFates.com/</PackageProjectUrl>
    <PackageIcon>Dark_noBG_face_256.png</PackageIcon>
    <PackageReleaseNotes>Added recursive functionality.</PackageReleaseNotes>
    <PackageTags>Debug; Debugging; Visual; Graphing; Graph; Variables; Variable; Runtime; Realtime; Live</PackageTags>
    <Copyright>Copyright © JackOfFates 2024</Copyright>
    <Version>1.1.2.0</Version>
    <PackageLicenseFile>License.txt</PackageLicenseFile>
    <PackageReadmeFile>JackDebug_README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/JackOfFates/Jack-Debug</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="favicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MahApps.Metro" Version="2.4.10" />
    <PackageReference Include="MicroSerializationLibrary" Version="1.1.2.22" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
  </ItemGroup>
	
  <ItemGroup>
    <Import Include="System.Drawing" />
  </ItemGroup>
	
  <ItemGroup>
    <Compile Update="My Project\Resources.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
	
  <ItemGroup>
    <EmbeddedResource Update="My Project\Resources.resx">
      <CustomToolNamespace>My.Resources</CustomToolNamespace>
      <Generator>VbMyResourcesResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.vb</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
	
  <ItemGroup>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
